# 开发环境配置文件

server:
  port: 8081     # Springboot占用端口

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver     # 数据库驱动
      url: jdbc:mysql://localhost:3306/seed?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false     # 数据库链接
      username: root     # 数据库账号
      password: root     # 数据库密码
  devtools:
    restart:
      enabled: true     # 开启热更新